### ISSUE TITLE
Comparison to Sørensen–Dice coefficient

### ISSUE THREAD

**Issue by dumblob** [nickeldan/dam_lev#2]
I wonder how these two compare (quality, human expactation satisfiability, performance, implementation constraints wise, etc.).

---

https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient

**Comment by dumblob** [comment]
I am asking mainly to gather some more evidence about string comparison algos to gain better understanding of where to deploy them and why.

**Comment by nickeldan** [comment]
Hm, it looks like the algorithms are doing different things.  The Sorensen-Dice coefficient is a non-integral value that looks at the common elements between two *unordered* collections.  The Damerau-Levenshtein algorithm, on the other hand, take order into account and tells you exactly one sequence would be transformed into the other.

**Comment by dumblob** [comment]
Yes, that is true. Generally though (and I am sorry for not being explicit about this) both are mostly being deployed to present alternatives to the user (e.g. when searching through a text or DB or when the user typed an error or "presumably an error" etc.).

Do you have any observations in this regard concerning quality, human expactation satisfiability, performance, implementation constraints wise, etc.?

**Comment by nickeldan** [comment]
I don't.  This project came out of a specific need I had for a project at work.

**Comment by dumblob** [comment]
Oh, I see. Closing for lack of actionable items then.

Anyone can further comment if anything interesting comes up :wink:.
